sudo: required
services:
  - docker

before_install:
  - docker build -t maruthi2398/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maruthi2398/react-test npm test

after_success:
  - docker build -t maruthi2398/multi-client ./client
  - docker build -t maruthi2398/multi-nginx ./nginx
  - docker build -t maruthi2398/multi-server ./server
  - docker build -t maruthi2398/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  
  - docker push maruthi2398/multi-client
  - docker push maruthi2398/multi-nginx
  - docker push maruthi2398/multi-server
  - docker push maruthi2398/multi-worker